version: "3.3"

services:
  relay:
    image: uk-london-1.ocir.io/lrqqxehccngb/streamway-injest:v1
    networks:
      - traefik-public
    environment:
      RTMP_PUSH_URLS: "rtmp://gopal.streamway.in/live/injest"
      #INJEST_API_HOST": "http://host.docker.internal:3000"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    deploy:
      labels:
        - traefik.enable=false
        
        

networks:
  traefik-public:
    external: true